// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

package manifest

import (
	"crypto/sha256"
	"encoding/hex"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestReadManifest_Empty(t *testing.T) {
	dir := t.TempDir()
	m := NewManager(dir)

	entries, err := m.ReadManifest()
	if err != nil {
		t.Fatalf("ReadManifest on nonexistent file: %v", err)
	}
	if len(entries) != 0 {
		t.Fatalf("expected empty slice, got %d entries", len(entries))
	}
}

func TestReadManifest_WithEntries(t *testing.T) {
	dir := t.TempDir()
	rawDir := filepath.Join(dir, "raw")
	if err := os.MkdirAll(rawDir, 0750); err != nil {
		t.Fatal(err)
	}

	content := "# Auto-generated by agent-kb. Do not edit manually.\n# filename | sha256 | last_updated\ndata.csv | abc123 | 2026-04-20T10:00:00Z\nimages/logo.png | def456 | 2026-04-20T11:00:00Z\n"
	if err := os.WriteFile(filepath.Join(rawDir, "files.log"), []byte(content), 0600); err != nil {
		t.Fatal(err)
	}

	m := NewManager(dir)
	entries, err := m.ReadManifest()
	if err != nil {
		t.Fatalf("ReadManifest: %v", err)
	}

	if len(entries) != 2 {
		t.Fatalf("expected 2 entries, got %d", len(entries))
	}

	if entries[0].Filename != "data.csv" {
		t.Errorf("entry[0].Filename = %q, want %q", entries[0].Filename, "data.csv")
	}
	if entries[0].SHA256 != "abc123" {
		t.Errorf("entry[0].SHA256 = %q, want %q", entries[0].SHA256, "abc123")
	}
	if entries[0].LastUpdated != "2026-04-20T10:00:00Z" {
		t.Errorf("entry[0].LastUpdated = %q, want %q", entries[0].LastUpdated, "2026-04-20T10:00:00Z")
	}

	if entries[1].Filename != "images/logo.png" {
		t.Errorf("entry[1].Filename = %q, want %q", entries[1].Filename, "images/logo.png")
	}
}

func TestReadManifest_CommentsSkipped(t *testing.T) {
	dir := t.TempDir()
	rawDir := filepath.Join(dir, "raw")
	if err := os.MkdirAll(rawDir, 0750); err != nil {
		t.Fatal(err)
	}

	content := "# comment line 1\n# comment line 2\ndata.csv | abc123 | 2026-04-20T10:00:00Z\n"
	if err := os.WriteFile(filepath.Join(rawDir, "files.log"), []byte(content), 0600); err != nil {
		t.Fatal(err)
	}

	m := NewManager(dir)
	entries, err := m.ReadManifest()
	if err != nil {
		t.Fatalf("ReadManifest: %v", err)
	}

	if len(entries) != 1 {
		t.Fatalf("expected 1 entry, got %d", len(entries))
	}
	if entries[0].Filename != "data.csv" {
		t.Errorf("entry.Filename = %q, want %q", entries[0].Filename, "data.csv")
	}
}

func TestReadManifest_CorruptedLine(t *testing.T) {
	dir := t.TempDir()
	rawDir := filepath.Join(dir, "raw")
	if err := os.MkdirAll(rawDir, 0750); err != nil {
		t.Fatal(err)
	}

	content := "# header\ncorrupted_line_no_pipes\n"
	if err := os.WriteFile(filepath.Join(rawDir, "files.log"), []byte(content), 0600); err != nil {
		t.Fatal(err)
	}

	m := NewManager(dir)
	_, err := m.ReadManifest()
	if err == nil {
		t.Fatal("expected error for corrupted line, got nil")
	}

	if !strings.Contains(err.Error(), "corrupted") {
		t.Errorf("error should mention 'corrupted', got: %v", err)
	}
	if !strings.Contains(err.Error(), "line 2") {
		t.Errorf("error should mention line number, got: %v", err)
	}
	if !strings.Contains(err.Error(), "akb raw sync") {
		t.Errorf("error should mention recovery command, got: %v", err)
	}
}

func TestWriteManifest(t *testing.T) {
	dir := t.TempDir()
	m := NewManager(dir)

	entries := []Entry{
		{Filename: "data.csv", SHA256: "abc123", LastUpdated: "2026-04-20T10:00:00Z"},
		{Filename: "images/logo.png", SHA256: "def456", LastUpdated: "2026-04-20T11:00:00Z"},
	}

	if err := m.WriteManifest(entries); err != nil {
		t.Fatalf("WriteManifest: %v", err)
	}

	readBack, err := m.ReadManifest()
	if err != nil {
		t.Fatalf("ReadManifest after write: %v", err)
	}

	if len(readBack) != 2 {
		t.Fatalf("expected 2 entries, got %d", len(readBack))
	}

	if readBack[0].Filename != "data.csv" {
		t.Errorf("entry[0].Filename = %q, want %q", readBack[0].Filename, "data.csv")
	}
	if readBack[1].Filename != "images/logo.png" {
		t.Errorf("entry[1].Filename = %q, want %q", readBack[1].Filename, "images/logo.png")
	}

	data, err := os.ReadFile(m.manifestPath()) //nolint:gosec // test reading known temp file
	if err != nil {
		t.Fatal(err)
	}
	header := "# Auto-generated by agent-kb. Do not edit manually.\n# filename | sha256 | last_updated\n"
	if !strings.HasPrefix(string(data), header) {
		t.Errorf("manifest should start with header, got:\n%s", string(data)[:minInt(len(data), len(header))])
	}
}

func TestAddEntry(t *testing.T) {
	dir := t.TempDir()
	m := NewManager(dir)

	if err := m.AddEntry("data.csv", "abc123"); err != nil {
		t.Fatalf("AddEntry: %v", err)
	}

	entries, err := m.ReadManifest()
	if err != nil {
		t.Fatalf("ReadManifest: %v", err)
	}

	if len(entries) != 1 {
		t.Fatalf("expected 1 entry, got %d", len(entries))
	}
	if entries[0].Filename != "data.csv" {
		t.Errorf("entry.Filename = %q, want %q", entries[0].Filename, "data.csv")
	}
	if entries[0].SHA256 != "abc123" {
		t.Errorf("entry.SHA256 = %q, want %q", entries[0].SHA256, "abc123")
	}
	if entries[0].LastUpdated == "" {
		t.Error("entry.LastUpdated should not be empty")
	}
}

func TestRemoveEntry(t *testing.T) {
	dir := t.TempDir()
	m := NewManager(dir)

	if err := m.AddEntry("data.csv", "abc123"); err != nil {
		t.Fatalf("AddEntry: %v", err)
	}
	if err := m.AddEntry("other.csv", "def456"); err != nil {
		t.Fatalf("AddEntry: %v", err)
	}

	if err := m.RemoveEntry("data.csv"); err != nil {
		t.Fatalf("RemoveEntry: %v", err)
	}

	entries, err := m.ReadManifest()
	if err != nil {
		t.Fatalf("ReadManifest: %v", err)
	}

	if len(entries) != 1 {
		t.Fatalf("expected 1 entry after removal, got %d", len(entries))
	}
	if entries[0].Filename != "other.csv" {
		t.Errorf("remaining entry.Filename = %q, want %q", entries[0].Filename, "other.csv")
	}
}

func TestUpdateEntry(t *testing.T) {
	dir := t.TempDir()
	m := NewManager(dir)

	if err := m.AddEntry("data.csv", "abc123"); err != nil {
		t.Fatalf("AddEntry: %v", err)
	}

	if err := m.UpdateEntry("data.csv", "updated_hash"); err != nil {
		t.Fatalf("UpdateEntry: %v", err)
	}

	entries, err := m.ReadManifest()
	if err != nil {
		t.Fatalf("ReadManifest: %v", err)
	}

	if len(entries) != 1 {
		t.Fatalf("expected 1 entry, got %d", len(entries))
	}
	if entries[0].SHA256 != "updated_hash" {
		t.Errorf("entry.SHA256 = %q, want %q", entries[0].SHA256, "updated_hash")
	}
	if entries[0].LastUpdated == "" {
		t.Error("entry.LastUpdated should be updated")
	}
}

func TestUpdateEntry_NotFound(t *testing.T) {
	dir := t.TempDir()
	m := NewManager(dir)

	err := m.UpdateEntry("nonexistent.csv", "hash")
	if err == nil {
		t.Fatal("expected error for nonexistent entry, got nil")
	}
	if !strings.Contains(err.Error(), "not found") {
		t.Errorf("error should mention 'not found', got: %v", err)
	}
}

func TestFindByFilename_Found(t *testing.T) {
	dir := t.TempDir()
	m := NewManager(dir)

	if err := m.AddEntry("data.csv", "abc123"); err != nil {
		t.Fatalf("AddEntry: %v", err)
	}

	entry, found, err := m.FindByFilename("data.csv")
	if err != nil {
		t.Fatalf("FindByFilename: %v", err)
	}
	if !found {
		t.Fatal("expected found=true")
	}
	if entry.Filename != "data.csv" {
		t.Errorf("entry.Filename = %q, want %q", entry.Filename, "data.csv")
	}
}

func TestFindByFilename_NotFound(t *testing.T) {
	dir := t.TempDir()
	m := NewManager(dir)

	entry, found, err := m.FindByFilename("nonexistent.csv")
	if err != nil {
		t.Fatalf("FindByFilename: %v", err)
	}
	if found {
		t.Fatal("expected found=false for nonexistent entry")
	}
	if entry != nil {
		t.Fatal("expected nil entry for nonexistent file")
	}
}

func TestValidateFilename_Pipe(t *testing.T) {
	err := ValidateFilename("file|name")
	if err == nil {
		t.Fatal("expected error for filename with '|'")
	}
	if !strings.Contains(err.Error(), "'|'") {
		t.Errorf("error should mention '|', got: %v", err)
	}
}

func TestValidateFilename_Newline(t *testing.T) {
	err := ValidateFilename("file\nname")
	if err == nil {
		t.Fatal("expected error for filename with newline")
	}
	if !strings.Contains(err.Error(), "newline") {
		t.Errorf("error should mention 'newline', got: %v", err)
	}
}

func TestValidateFilename_FilesLog(t *testing.T) {
	err := ValidateFilename("files.log")
	if err == nil {
		t.Fatal("expected error for filename 'files.log'")
	}
	if !strings.Contains(err.Error(), "managed file") {
		t.Errorf("error should mention 'managed file', got: %v", err)
	}
}

func TestValidateFilename_Valid(t *testing.T) {
	names := []string{"data.csv", "images/logo.png", "report-2026.pdf"}
	for _, name := range names {
		if err := ValidateFilename(name); err != nil {
			t.Errorf("ValidateFilename(%q): unexpected error: %v", name, err)
		}
	}
}

func TestComputeSHA256(t *testing.T) {
	dir := t.TempDir()
	content := []byte("hello, world")
	f, err := os.CreateTemp(dir, "sha256test")
	if err != nil {
		t.Fatal(err)
	}
	if _, err := f.Write(content); err != nil {
		t.Fatal(err)
	}
	if err := f.Close(); err != nil {
		t.Fatal(err)
	}

	expected := sha256.Sum256(content)
	expectedHex := hex.EncodeToString(expected[:])

	got, err := ComputeSHA256(f.Name())
	if err != nil {
		t.Fatalf("ComputeSHA256: %v", err)
	}

	if got != expectedHex {
		t.Errorf("ComputeSHA256 = %q, want %q", got, expectedHex)
	}
}

func TestWriteManifest_AtomicWrite(t *testing.T) {
	dir := t.TempDir()
	m := NewManager(dir)

	entries := []Entry{
		{Filename: "data.csv", SHA256: "abc123", LastUpdated: "2026-04-20T10:00:00Z"},
	}

	if err := m.WriteManifest(entries); err != nil {
		t.Fatalf("WriteManifest: %v", err)
	}

	// Verify no temp files remain
	rawDir := filepath.Join(dir, "raw")
	entriesDir, err := os.ReadDir(rawDir)
	if err != nil {
		t.Fatal(err)
	}

	for _, e := range entriesDir {
		if strings.HasPrefix(e.Name(), "files.log.") {
			t.Errorf("temp file left behind: %s", e.Name())
		}
	}
}

func minInt(a, b int) int {
	if a < b {
		return a
	}
	return b
}
