// Package manifest manages the raw/files.log manifest that tracks
// uploaded files with their SHA-256 hashes and timestamps.
package manifest

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// Entry represents a single file tracked in the manifest.
type Entry struct {
	Filename    string // relative path from raw/ (e.g., "data.csv" or "images/logo.png")
	SHA256      string // hex-encoded SHA-256 hash
	LastUpdated string // ISO 8601 timestamp
}

// Manager handles reading, writing, and modifying the manifest file.
type Manager struct {
	kbRoot string
}

// NewManager creates a new manifest Manager for the given KB root.
func NewManager(kbRoot string) *Manager {
	return &Manager{kbRoot: kbRoot}
}

// manifestPath returns the path to the manifest file.
func (m *Manager) manifestPath() string {
	return filepath.Join(m.kbRoot, "raw", "files.log")
}

// ReadManifest parses the manifest file and returns its entries.
// If the file doesn't exist, it returns an empty slice (not an error).
// Comment lines (starting with #) are skipped.
// Invalid lines produce an actionable error message.
func (m *Manager) ReadManifest() ([]Entry, error) {
	path := m.manifestPath()

	data, err := os.ReadFile(path) //nolint:gosec // path constructed by manifestPath within KB root
	if err != nil {
		if os.IsNotExist(err) {
			return []Entry{}, nil
		}
		return nil, fmt.Errorf("read manifest: %w", err)
	}

	var entries []Entry
	lines := strings.Split(string(data), "\n")
	for i, line := range lines {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" || strings.HasPrefix(trimmed, "#") {
			continue
		}

		parts := strings.SplitN(trimmed, "|", 3)
		if len(parts) != 3 {
			return nil, fmt.Errorf("raw/files.log is corrupted: line %d has invalid format; run 'akb raw sync' to rebuild", i+1)
		}

		filename := strings.TrimSpace(parts[0])
		sha256hash := strings.TrimSpace(parts[1])
		timestamp := strings.TrimSpace(parts[2])

		entries = append(entries, Entry{
			Filename:    filename,
			SHA256:      sha256hash,
			LastUpdated: timestamp,
		})
	}

	return entries, nil
}

// WriteManifest writes the header and entries to the manifest file.
// It uses atomic write (temp file + rename) to avoid corruption.
func (m *Manager) WriteManifest(entries []Entry) error {
	path := m.manifestPath()

	if err := os.MkdirAll(filepath.Dir(path), 0750); err != nil {
		return fmt.Errorf("create manifest directory: %w", err)
	}

	var sb strings.Builder
	sb.WriteString("# Auto-generated by agent-kb. Do not edit manually.\n")
	sb.WriteString("# filename | sha256 | last_updated\n")
	for _, e := range entries {
		fmt.Fprintf(&sb, "%s | %s | %s\n", e.Filename, e.SHA256, e.LastUpdated)
	}

	tmpFile, err := os.CreateTemp(filepath.Dir(path), "files.log.*")
	if err != nil {
		return fmt.Errorf("create temp file: %w", err)
	}
	tmpPath := tmpFile.Name()

	if _, err := tmpFile.WriteString(sb.String()); err != nil {
		_ = tmpFile.Close()    //nolint:errcheck // close error secondary to write error
		_ = os.Remove(tmpPath) //nolint:errcheck // cleanup on failure — secondary to write error
		return fmt.Errorf("write temp manifest: %w", err)
	}

	if err := tmpFile.Close(); err != nil {
		_ = os.Remove(tmpPath) //nolint:errcheck // cleanup on failure — secondary to close error
		return fmt.Errorf("close temp manifest: %w", err)
	}

	if err := os.Rename(tmpPath, path); err != nil {
		_ = os.Remove(tmpPath) //nolint:errcheck // cleanup on failure — secondary to rename error
		return fmt.Errorf("rename temp manifest: %w", err)
	}

	return nil
}

// AddEntry appends a new entry to the manifest.
// It validates the filename, reads the current manifest, appends the entry,
// and writes the manifest back.
func (m *Manager) AddEntry(filename, sha256hash string) error {
	if err := ValidateFilename(filename); err != nil {
		return err
	}

	entries, err := m.ReadManifest()
	if err != nil {
		return fmt.Errorf("read manifest: %w", err)
	}

	entries = append(entries, Entry{
		Filename:    filename,
		SHA256:      sha256hash,
		LastUpdated: time.Now().UTC().Format(time.RFC3339),
	})

	return m.WriteManifest(entries)
}

// RemoveEntry removes an entry from the manifest by filename.
// If the filename is not found, it returns nil (no error).
func (m *Manager) RemoveEntry(filename string) error {
	entries, err := m.ReadManifest()
	if err != nil {
		return fmt.Errorf("read manifest: %w", err)
	}

	filtered := make([]Entry, 0, len(entries))
	for _, e := range entries {
		if e.Filename != filename {
			filtered = append(filtered, e)
		}
	}

	return m.WriteManifest(filtered)
}

// UpdateEntry updates an existing entry's SHA-256 hash and timestamp.
// If the filename is not found, it returns an error.
func (m *Manager) UpdateEntry(filename, sha256hash string) error {
	entries, err := m.ReadManifest()
	if err != nil {
		return fmt.Errorf("read manifest: %w", err)
	}

	found := false
	for i := range entries {
		if entries[i].Filename == filename {
			entries[i].SHA256 = sha256hash
			entries[i].LastUpdated = time.Now().UTC().Format(time.RFC3339)
			found = true
			break
		}
	}

	if !found {
		return fmt.Errorf("entry not found: %s", filename)
	}

	return m.WriteManifest(entries)
}

// FindByFilename looks up an entry by filename.
// Returns the entry and true if found, or nil and false if not.
func (m *Manager) FindByFilename(filename string) (*Entry, bool, error) {
	entries, err := m.ReadManifest()
	if err != nil {
		return nil, false, fmt.Errorf("read manifest: %w", err)
	}

	for i := range entries {
		if entries[i].Filename == filename {
			return &entries[i], true, nil
		}
	}

	return nil, false, nil
}

// ComputeSHA256 computes the SHA-256 hash of a file using streaming
// to avoid loading the entire file into memory.
func ComputeSHA256(filePath string) (string, error) {
	f, err := os.Open(filePath) //nolint:gosec // filePath is validated by caller
	if err != nil {
		return "", fmt.Errorf("open file for hashing: %w", err)
	}
	defer f.Close() //nolint:errcheck // file read complete via io.Copy; close error non-critical

	hash := sha256.New()
	if _, err := io.Copy(hash, f); err != nil {
		return "", fmt.Errorf("compute SHA-256: %w", err)
	}

	return hex.EncodeToString(hash.Sum(nil)), nil
}

// ValidateFilename checks that a filename is valid for use in the manifest.
// It rejects filenames containing '|', newlines, or the exact name "files.log".
func ValidateFilename(filename string) error {
	if strings.Contains(filename, "|") {
		return fmt.Errorf("filename must not contain '|'")
	}
	if strings.Contains(filename, "\n") {
		return fmt.Errorf("filename must not contain newlines")
	}
	if filename == "files.log" {
		return fmt.Errorf("files.log is a managed file, cannot be used as a filename")
	}
	return nil
}
