package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/spf13/cobra"

	"github.com/peedrr/agent-kb/internal/config"
	"github.com/peedrr/agent-kb/internal/db"
	"github.com/peedrr/agent-kb/internal/registry"
	"github.com/peedrr/agent-kb/internal/template"
)

var initCmd = &cobra.Command{
	Use:   "init <name>",
	Short: "Initialize a new Agent Knowledge Base",
	Long:  `Create a new KB directory with the standard structure, git repo, and configuration.`,
	Example: `  # Initialize a new KB and set as default
  akb init my-kb

  # Initialize a KB in a specific directory
  akb init projects/knowledge`,
	Args: cobra.ExactArgs(1),
	RunE: runInit,
}

func runInit(_ *cobra.Command, args []string) error {
	name := args[0]

	if err := validateName(name); err != nil {
		return err
	}

	if _, err := os.Stat(filepath.Join(name, ".akb")); err == nil {
		return fmt.Errorf("kb already initialized at %s. Use a different name or remove existing kb", name)
	}

	if err := checkGitAvailable(); err != nil {
		return err
	}

	if err := createDirectoryStructure(name); err != nil {
		return err
	}

	if err := writeSeedFiles(name); err != nil {
		return err
	}

	now := time.Now().Format(time.RFC3339)
	if err := writeAkbConfig(name, now); err != nil {
		return err
	}

	if err := template.CopyDefaults(filepath.Join(name, ".akb", "templates")); err != nil {
		return fmt.Errorf("copy templates: %w", err)
	}

	if err := initSearchDB(name); err != nil {
		return err
	}

	if err := writeGitignoreFiles(name); err != nil {
		return err
	}

	if err := gitInitAndCommit(name); err != nil {
		return err
	}

	absPath, err := filepath.Abs(name)
	if err != nil {
		return fmt.Errorf("resolve absolute path: %w", err)
	}
	if err := registry.AddEntry(registry.Entry{
		Name:    name,
		Path:    absPath,
		Created: now,
	}); err != nil {
		return fmt.Errorf("add registry entry: %w", err)
	}

	regPath, err := registry.Path()
	if err != nil {
		return fmt.Errorf("get registry path: %w", err)
	}
	reg, err := registry.Load(regPath)
	if err != nil {
		return fmt.Errorf("load registry: %w", err)
	}

	if reg.Default == "" {
		if err := registry.SetDefault(name); err != nil {
			return fmt.Errorf("set default registry: %w", err)
		}
		fmt.Printf("Initialized KB %q at %s and set as default\n", name, absPath)
	} else {
		fmt.Printf("Initialized KB %q at %s\n", name, absPath)
	}
	return nil
}

func validateName(name string) error {
	if name == "" || strings.TrimSpace(name) == "" {
		return fmt.Errorf("name must not be empty")
	}
	if strings.Contains(name, "/") {
		return fmt.Errorf("name must not contain '/'")
	}
	if strings.Contains(name, "..") {
		return fmt.Errorf("name must not contain '..'")
	}
	if strings.HasPrefix(name, "-") {
		return fmt.Errorf("name must not start with '-'")
	}
	return nil
}

func checkGitAvailable() error {
	_, err := exec.LookPath("git")
	if err != nil {
		return fmt.Errorf("git is required but not found. Please install git")
	}
	return nil
}

func createDirectoryStructure(name string) error {
	dirs := []string{
		filepath.Join(name, "kb"),
		filepath.Join(name, "raw"),
		filepath.Join(name, ".akb", "templates"),
	}
	for _, dir := range dirs {
		if err := os.MkdirAll(dir, 0750); err != nil {
			return fmt.Errorf("create directory %s: %w", dir, err)
		}
	}
	return nil
}

func writeSeedFiles(name string) error {
	seeds := map[string]string{
		filepath.Join(name, "kb", "index.md"):   "# Index\n\n",
		filepath.Join(name, "kb", "log.md"):     "# Log\n\n",
		filepath.Join(name, "raw", "files.log"): "# Auto-generated by agent-kb. Do not edit manually.\n# filename | sha256 | last_updated\n",
	}
	for path, content := range seeds {
		if err := os.WriteFile(path, []byte(content), 0600); err != nil {
			return fmt.Errorf("write %s: %w", path, err)
		}
	}
	return nil
}

func writeAkbConfig(name, created string) error {
	cfg := &config.Config{
		Name:    name,
		Created: created,
	}
	if err := config.Save(filepath.Join(name, ".akb", ".akb.yaml"), cfg); err != nil {
		return fmt.Errorf("save config: %w", err)
	}
	return nil
}

func initSearchDB(name string) error {
	dbPath := filepath.Join(name, ".akb", "search.db")
	conn, err := db.InitDB(dbPath)
	if err != nil {
		return fmt.Errorf("init database: %w", err)
	}
	defer conn.Close() //nolint:errcheck // DB close error non-critical on command exit

	if _, err := conn.Exec("PRAGMA journal_mode=WAL"); err != nil {
		return fmt.Errorf("enable WAL mode: %w", err)
	}
	conn.SetMaxOpenConns(1)

	if err := db.CreateSchema(conn); err != nil {
		return fmt.Errorf("create schema: %w", err)
	}
	return nil
}

func writeGitignoreFiles(name string) error {
	akbGitignore := filepath.Join(name, ".akb", ".gitignore")
	if err := os.WriteFile(akbGitignore, []byte("search.db*\n"), 0600); err != nil {
		return fmt.Errorf("write .akb/.gitignore: %w", err)
	}

	rootGitignore := filepath.Join(name, ".gitignore")
	if err := os.WriteFile(rootGitignore, []byte("*.akb.bak\n.akb/search.db*\n"), 0600); err != nil {
		return fmt.Errorf("write .gitignore: %w", err)
	}
	return nil
}

func gitInitAndCommit(name string) error {
	absPath, err := filepath.Abs(name)
	if err != nil {
		return fmt.Errorf("resolve path: %w", err)
	}

	gitInit := exec.Command("git", "init", name) //nolint:gosec // launching trusted git binary with controlled args
	if out, err := gitInit.CombinedOutput(); err != nil {
		return fmt.Errorf("git init: %s: %w", strings.TrimSpace(string(out)), err)
	}

	if err := ensureGitConfig(absPath); err != nil {
		return err
	}

	gitAdd := exec.Command("git", "add", "-A")
	gitAdd.Dir = absPath
	if out, err := gitAdd.CombinedOutput(); err != nil {
		return fmt.Errorf("git add: %s: %w", strings.TrimSpace(string(out)), err)
	}

	commitMsg := fmt.Sprintf("akb: init %s", name)
	gitCommit := exec.Command("git", "commit", "-m", commitMsg) //nolint:gosec // launching trusted git binary with controlled args
	gitCommit.Dir = absPath
	if out, err := gitCommit.CombinedOutput(); err != nil {
		return fmt.Errorf("git commit: %s: %w", strings.TrimSpace(string(out)), err)
	}

	return nil
}

func ensureGitConfig(repoPath string) error {
	gitConfig := func(args ...string) (string, error) {
		cmd := exec.Command("git", args...) //nolint:gosec // launching trusted git binary with controlled args
		cmd.Dir = repoPath
		out, err := cmd.Output()
		return strings.TrimSpace(string(out)), err
	}

	if _, err := gitConfig("config", "user.name"); err != nil {
		if _, err := gitConfig("config", "user.name", "akb"); err != nil {
			return fmt.Errorf("set git user.name: %w", err)
		}
	}

	if _, err := gitConfig("config", "user.email"); err != nil {
		if _, err := gitConfig("config", "user.email", "akb@local"); err != nil {
			return fmt.Errorf("set git user.email: %w", err)
		}
	}

	return nil
}
